### ISSUE TITLE
Action Buttons not working

### ISSUE THREAD

**Issue by Girotin** [Ibrahim778/BetterHomebrewBrowser#1]
I had the issue of only being able to utilize the touchscreen, and the analog sticks to navigate between the options, the D-Pad and X,O, Square and Triangle didn't worked

Also, after opening the app, my entire Vita stopped working in everyone of these buttons I mentioned that didn't worked

Latest Version Tried: 0.3B

**Comment by Ibrahim778** [comment]
This is not a bug in my app but PSVShell. It is unable to detect the foreground app properly. As such it blocks the button inputs but doesn't show itself. The way to fix it is to hold select + Down (Dpad) until the buttons work again. As such you wont be able to use psvshell until you reboot. Ask Electric to fix it
