### ISSUE TITLE
Reproducable Crash 

### ISSUE THREAD

**Issue by Abbin44** [Ibrahim778/BetterHomebrewBrowser#11]
The application crashes if I select CBPS DB as the source, The crash occurs right when the "extracting" bar is finished. However, VitaDB works well. To me this sounds like it could have something to do with memory space, I have approximately 8GB free space on my SD card.

**Comment by Ibrahim778** [comment]
Go to settings - > DB Options -> CBPS DB -> Download Icons during load -> Set to Disabled

**Comment by Abbin44** [comment]
Yes that is a workaround. Just wanted to report a bug

**Comment by Ibrahim778** [comment]
Yea, I don't it can be helped. Just that CBPS DB has a few broken links, trying to dl them probably causes crashes or something

**Comment by Abbin44** [comment]
Is it not possible to surround the download in a try-catch?

**Comment by Ibrahim778** [comment]
Maybe? Although if that's not the issue it'll still do that.
