### ISSUE TITLE
Error 0x80101104

### ISSUE THREAD

**Issue by Kendy1905** [Ibrahim778/BetterHomebrewBrowser#13]
After update app on 61b cant install pls help!
![Uploading AAAABA3E-4AA5-49F8-8075-D6EF983074A9.jpeg…]()
![4D1AD446-C186-4034-9BD9-5A5F53DAB766](https://user-images.githubusercontent.com/95968938/145679015-ee10e35d-ee08-4bb1-a755-8c5ce3288feb.jpeg)

**Comment by Ibrahim778** [comment]
Delete ux0:temp

**Comment by Kendy1905** [comment]
> Delete ux0:temp

Have new problems 
![8A9363CC-2385-4FFB-B26D-7D7E5FD8FEFB](https://user-images.githubusercontent.com/95968938/145682385-72cf24fd-8d6c-4aaa-8282-0b16f7ee0e55.jpeg)

**Comment by Ibrahim778** [comment]
Sorry I meant everything in ux0:temp. Just make a new folder called temp in ux0:

**Comment by sanyabeast** [comment]
> Sorry I meant everything in ux0:temp. Just make a new folder called temp in ux0:

thank you. it helped me.
