### ISSUE TITLE
App freezes and crashes the entire console upon starting

### ISSUE THREAD

**Issue by Subarasheese** [Ibrahim778/BetterHomebrewBrowser#14]
Hello,

I'm using a Vita 1000, Henkaku Enso 3.60.

I installed the latest release of the app, V0.61B. When I run it, I can hear the music on the background but the entire system freezes. I can't even press the PS Button to go back to the live area, so I am forced to turn off the console (which makes the PS button blink).
This happens every time.

Is there a way I can provide logs to help with this issue? I have no idea how to get debugging logs from Vita.

**Comment by hedhehd** [comment]
I think this project is discontinued sadly.

**Comment by Ibrahim778** [comment]
It's not, I've just been busy for a loong while
I have started working on it again, expect something soon

**Comment by hedhehd** [comment]
Oh okay I'm looking forward to whatever feature is coming.

**Comment by wefalltomorrow** [comment]
> It's not, I've just been busy for a loong while I have started working on it again, expect something soon

Any updates? :)

**Comment by wefalltomorrow** [comment]
> Dang. School has really been annoying me for the past few months. Even though it's meant to be the holidays :( I have exams in october. And from what I expect of the school year I don't think I'll be able to find any more time for any of my projects anytime soon. I managed to make a small alpha which has a complete redesign but so far that's it. Sorry guys!

All good man, take all the time you need!
