### ISSUE TITLE
Hey could you make a VitaSDK source code?

### ISSUE THREAD

**Issue by hedhehd** [Ibrahim778/BetterHomebrewBrowser#15]
Because it will be easier to change stuff and build it.

I know VDSuite has some features that VitaSDK doesn't.

**Comment by Ibrahim778** [comment]
No; It's just not possible for public use.
You must use VDSuite

**Comment by Ibrahim778** [comment]
It is honestly impossible for anyone to build it unless they have unreleased paf headers. And the current public release also uses a bunch of messy curl headers. What exactly do you need to do?

**Comment by hedhehd** [comment]
Just wanted to make some edits and some new stuff. Why? Because I'm a beginner at programming but can get better if I do stuff like this.

**Comment by hedhehd** [comment]
I did the same for AutoPlugin II and made it remastered.

**Comment by devingDev** [comment]
It works :tm: just use the vdsuite and if you want it ported do it yourself
