### ISSUE TITLE
Can't change categories

### ISSUE THREAD

**Issue by orangelampshade** [Ibrahim778/BetterHomebrewBrowser#23]
When trying to navigate to other categories using the touchpad or joystick (all>games>emulation etc), nothing happens. When i use to arrow button to navigate left to right, the list changes but the 'ALL' category remains highlighted. This means I don't know which category i am in. Thanks

**Comment by Ibrahim778** [comment]
Strange, which DB were you using. Did you switch the DB's before this happening?

**Comment by orangelampshade** [comment]
No I didn’t switch them but I tried afterwards to see if it changed anything.

Hopefully this video shows you what I mean.



Thanks
Jacob

On 14 Mar 2023, at 7:14 pm, Ibrahim ***@***.***> wrote:

﻿

Strange, which DB were you using. Did you switch the DB's before this happening?

**Comment by orangelampshade** [comment]
Ok hopefully this works. 

https://user-images.githubusercontent.com/58881250/225444570-67c716a5-f17c-434b-8740-5e7561a83a78.MOV

**Comment by Ibrahim778** [comment]
Ah I see, is this immediately after startup? you didn't browse around before did you and, Have you tried changing to CBPS-DB and then back?

**Comment by orangelampshade** [comment]
Yea and also after browsing. I tried changing back to vita db and the categories started working but it crashed:
An error has occurred in the following application.
(C2-12828-1)
Saved Core File Succeeded. ux0:data/psp2core-1678947154-0x0000072b0b-eboot.bin.psp2dmp

Then I tried switching between categories on my other slim vita and it crashed. Same error.

**Comment by Ibrahim778** [comment]
The crash looks like an issue with the old icon system. You'll have to wait for the new update I'm afraid.
Sadly it seems that's many months away

**Comment by orangelampshade** [comment]
All good, there’s no rush. I just thought I’d bring it to your attention. Cheers.

**Comment by Ibrahim778** [comment]
A new version has been released, this issue should be fixed. Feel free to re-open if it isn't.
