### ISSUE TITLE
Cannot download anything 

### ISSUE THREAD

**Issue by Backontrack64** [Ibrahim778/BetterHomebrewBrowser#25]
It says could not find a valid source for download

What happens is that I click download and it says that "could not find a valid source for download"

Only a few apps can be downloaded for some reason and won't say the line

![Uploading 16874202308104093963176582494722.jpg…]()

**Comment by Ibrahim778** [comment]
That photo is broken.
This should not be a bug. Some links are either just invalid or can't be downloaded from the vita.
However, **all** links from VitaDB should work, just some links in CBPS-DB can have issues.

**Comment by Backontrack64** [comment]
Thanks I'll be closing this issue now

**Comment by Backontrack64** [comment]
Fixed turns out some links can't be downloaded only some can

**Comment by Ibrahim778** [comment]
Which links were you trying and with which DB?
I poorly worded what I meant, it's the fact that CBPS-DB has a lot of broken links that are the problem.
