### ISSUE TITLE
(C2-12928-1)

### ISSUE THREAD

**Issue by Orestes-Tactical** [Ibrahim778/BetterHomebrewBrowser#29]
Evening all, 

I'm a bit out of touch with the Vita scene, (due to two small kids and wife)  so my vita is probably on outdated stuff, at last check my Vita is on h-encore 3.68. (Spoofed 3.74).  I saw a recent video on your product and installed iTLS-Enso today (literally the latest release) as recommended.  

Unfortunately I'm getting the (C2-12928-1) error.  

I'll be honest, I'll probably need specific guidance, I'm competent just out of touch by a year or three 🤣🤣

Kindest thanks 

James

**Comment by Ibrahim778** [comment]
The C2-12928-1 error is a crash.
Also it's not a valid code either.
Try reinstalling?

**Comment by Orestes-Tactical** [comment]
Thank you,

**Comment by AnalogMan151** [comment]
My VitaShell crashes with this error (C2-12928-1) when attempting to install the v1.1 VPK. Tried multiple times, tried restarting, tried re-downloading and copying the VPK over. Each attempt results in the same crash immediately.

**Comment by Ibrahim778** [comment]
It's quite strange how so many people are reporting this now. Never happened before.
Anywhoo, I've replaced the VPK file in the release so give it a redownload and see if it fixes anything
