### ISSUE TITLE
Translation Chinese  language (zh.xml)

### ISSUE THREAD

**Issue by michael-moon-lee** [Ibrahim778/BetterHomebrewBrowser#33]
[zh.xml.zip](https://github.com/Ibrahim778/BetterHomebrewBrowser/files/12318173/zh.xml.zip)
Translation Chinese  language (zh.xml)

**Comment by Ibrahim778** [comment]
Thanks, I have set this for both Chinese (Simplified) and Chinese (Traditional) in V1.3. Let me know if this needs changing.

**Comment by michael-moon-lee** [comment]
msg_credits spelling translation error😂

**Comment by michael-moon-lee** [comment]
sorry....msg_credits spelling translation error😂

correct is the "制作人员"
