### ISSUE TITLE
Fix Chinese translation errors

### ISSUE THREAD

**Issue by michael-moon-lee** [Ibrahim778/BetterHomebrewBrowser#37]
[zh.xml.zip](https://github.com/Ibrahim778/BetterHomebrewBrowser/files/12364325/zh.xml.zip)
Fix translation errors You can use it when you update next time

sorry....msg_credits spelling translation error😂

correct is the "制作人员"
![261023942-7b6cfde0-2690-4202-a22c-facfe62fb071](https://github.com/Ibrahim778/BetterHomebrewBrowser/assets/36118880/2e6d6dfb-bf93-4c66-ab27-a95afd6f2849)

**Comment by michael-moon-lee** [comment]
[zh.xml.zip](https://github.com/Ibrahim778/BetterHomebrewBrowser/files/12365747/zh.xml.zip)
fix [download_button_text] text VPK

**Comment by Ibrahim778** [comment]
This has been fixed in V1.31
