### ISSUE TITLE
Cannot self-update in the app

### ISSUE THREAD

**Issue by carcaschoi** [Ibrahim778/BetterHomebrewBrowser#7]

**Comment by hedhehd** [comment]
I think this project is discontinued sadly.

**Comment by Girotin** [comment]
F

It was such an amazing project, sadly it died before managing to reach it's full potential.
At least it's already better than og Lua's HBB

**Comment by Ibrahim778** [comment]
See #14

**Comment by Girotin** [comment]
Oh that makes me happy :)

Take all the time you need bro, best wishes for your dev
