### ISSUE TITLE
Error 0x80101104

### ISSUE THREAD

**Issue by MrBruhh** [Ibrahim778/BetterHomebrewBrowser#8]
For some reason every time I try to download an app it gives me this error, I hope this can be fixed in the 0.61 version!

**Comment by Ibrahim778** [comment]
Which app are you trying to download? Have you tried terminating bgdl and rebooting?

**Comment by MrBruhh** [comment]
Soooo the error still remains for some reason, any idea why?

**Comment by MrBruhh** [comment]
> Which app are you trying to download? Have you tried terminating bgdl and rebooting?

So I'm tried to download bartender and RetroFlow Launcher, still getting the error. And yes I tried rebooting and what is terminating bgdl?

**Comment by Ibrahim778** [comment]
Not sure why you're getting that...They both download fine for me. Go to settings -> Other -> Terminate BGDL and reboot

**Comment by MrBruhh** [comment]
> Not sure why you're getting that...They both download fine for me. Go to settings -> Other -> Terminate BGDL and reboot

Reboot the console?

**Comment by MrBruhh** [comment]
sooo I pressed terminate BGDL, rebooted the console, started to download sonic 2 sms remake and after the prompting phase and still it gives me the 0x80101104

**Comment by SwooodGa** [comment]
_(Info from devnoname120 gist)_
0x80101104 = trying to install a VPK that has a corrupted entry in the vita db 
(edit ur0:/shell/db/app.db to get rid of it, and delete the ux0:/app/thebrokenapp folder)

As for me: I haven't had this happen with versions 0.51b and 0.61b.

**Comment by MrBruhh** [comment]
> _(Info from devnoname120 gist)_
> 
> 0x80101104 = trying to install a VPK that has a corrupted entry in the vita db 
> 
> (edit ur0:/shell/db/app.db to get rid of it, and delete the ux0:/app/thebrokenapp folder)
> 
> 
> 
> As for me: I haven't had this happen with versions 0.51b and 0.61b.
![image](https://user-images.githubusercontent.com/65976587/142003759-c4016fe3-cc91-449b-9cb5-39a217ffce6e.jpeg)

The problem is that bhbb doesn't download the homebrew, just showing this error. and I think that any homebrew wouldn't download

**Comment by MrBruhh** [comment]
and also I tried downloading from other homebrew browsers and everything works fine

**Comment by ACViper** [comment]
I am also having the same problem. It is the only homebrew browser I get error 0x80101104 when I try to install something.

**Comment by SwooodGa** [comment]
Maybe installing CapUnlocker or iTLS fix this?

**Comment by MrBruhh** [comment]
I think I have both of them are installed

**Comment by Ibrahim778** [comment]
Interesting......Does ux0:temp and ux0:temp/app exist?

**Comment by MrBruhh** [comment]
yep

**Comment by Ibrahim778** [comment]
There's your issue lmao. Delete ux0:temp/app

**Comment by MrBruhh** [comment]
OHHHH YEP THAT WAS THE PROBLEM….

**Comment by MrBruhh** [comment]
also I have a question, can I download things in sleep mode?

**Comment by Ibrahim778** [comment]
Yes? Maybe? Honestly I never tried, but it should be possible

**Comment by MrBruhh** [comment]
> Yes? Maybe? Honestly I never tried, but it should be possible
> 
> Ok I just checked, no you cannot as of now. I will do it later.

ok thanks! gonna wait for that feature
